name: ALB Controller Helm Provisioning

on:
  workflow_dispatch:

  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  alb-controller-provision:
    name: ALB Controller Helm Provisioning
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Iac/Terraform/helm-charts/alb-controller

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412058343270:role/github-terraform-role
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=flaskapp-terraform-state" \
            -backend-config="key=helm-charts/alb-controller/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="envs/dev.tfvars" -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: alb-controller-plan
          path: Iac/Terraform/helm-charts/alb-controller/tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
