name: Management Infrastructure Provisioning

on:
  workflow_dispatch:
    
  pull_request:
    paths:
      - "Iac/**"
      - ".github/workflows/infrastructure-provisioning.yml"

  push:
    paths:
      - "Iac/**"
      - ".github/workflows/infrastructure-provisioning.yml"

permissions:
  contents: read
  id-token: write

jobs:
  infrastructure-provisioning:
    name: Infrastructure Provisioning (VPC + EKS + IAM)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Iac/Terraform/envs/dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412058343270:role/github-terraform-role
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init     

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: infrastructure-plan
          path: Iac/Terraform/envs/dev/tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

  alb-controller-provision:
    name: ALB Controller Helm Provisioning
    needs: infrastructure-provisioning
    uses: ./.github/workflows/alb-controller-helm.yml