name: Infrastructure Deprovisioning

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:

  infrastructure-deprovisioning:
    name: Infrastructure Deprovisioning
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Iac/Terraform/envs/dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412058343270:role/github-terraform-role
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve tfplan