name: Management Infrastructure Provisioning

on:
  pull_request:
    paths:
      - "Iac/**"
      - ".github/workflows/terraform.yml"

  push:
    branches:
      - main
    paths:
      - "Iac/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Iac/Terraform/envs/dev
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426449772112:role/github-terraform-role
          aws-region: ap-southeast-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Format Check
      #   run: terraform fmt -check      

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan  
